### ISSUE TITLE
【功能】增加图片处理

### ISSUE THREAD

**Issue by Celeter** [emptysuns/18comic-Download#1]
最新章的图片图片都被切割过需要处理

**Comment by emptysuns** [comment]
您好，已经增加了图片处理机制。并且优化了，使用效果，如果还有问题，欢迎issue提出

**Comment by Celeter** [comment]
> 您好，已经增加了图片处理机制。并且优化了使用效果，如果还有问题，欢迎issue提出。

图片重新拼接部分
![image](https://user-images.githubusercontent.com/48249130/105150635-f8ca3200-5b3f-11eb-9962-53c1dda24a26.png)

判断是否需要拼接
![image](https://user-images.githubusercontent.com/48249130/105150739-19928780-5b40-11eb-9e49-9e14f3b85180.png)

aid、scramble_id、speed这三个参数可从html中爬取

**Comment by Celeter** [comment]
这是我写的图片拼接
![image](https://user-images.githubusercontent.com/48249130/105151158-97ef2980-5b40-11eb-99b4-c795766003c5.png)

**Comment by emptysuns** [comment]
谢谢参与交流，指正我代码中不妥部分。我会尝试参考您指出的”通过**前端**分析的方法”判断是否经过图片拼接，而不是简单的通过id值判断。
我会在下个版本，加入您所指出的方法。
