### ISSUE TITLE
图片错乱

### ISSUE THREAD

**Issue by lxw9518** [emptysuns/18comic-Download#12]
有问题请教这个图片错位问题！！！我看了大部分的图片，，不能10分切割，，有的是2有的6有的10有的20！！无法统一，这个应该怎么解决

**Comment by maoyj** [comment]
能不能举几个样本？可能纵向尺寸不一样。原站也是用代码纠正图片的。

**Comment by lxw9518** [comment]
原站的确也是用canvs画出来的，但是没找到每张图片的切割次数




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "emptysuns/18comic-Download"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月10日(星期二) 上午7:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [emptysuns/18comic-Download] 图片错乱 (#12)





 
能不能举几个样本？可能纵向尺寸不一样。原站也是用代码纠正图片的。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by emptysuns** [comment]
有js代码是处理切割，当时是为了方便码字写的10，可以自行找找源站前端代码。被官方找过后，我已经不再维护了。 ---- On 星期二, 10 八月 2021 01:34:19 +0800  ***@***.***  wrote ----

有问题请教这个图片错位问题！！！我看了大部分的图片，，不能10分切割，，有的是2有的6有的10有的20！！无法统一，这个应该怎么解决
