### ISSUE TITLE
是不是要处理反爬啊，比如这个漫画 227153

### ISSUE THREAD

**Issue by gMan1990** [emptysuns/18comic-Download#2]
id: `227153`

**Comment by emptysuns** [comment]
经过测试，您所说的 https://18comic.org/photo/227153/ 单独这个页面并未做过任何反爬机制
我经测试脚本成功下载了49张jpeg漫画，下面是结果实例:
https://i.loli.net/2021/01/19/sed92YlQicDqVSG.png

请您在通畅的网络下，再试一试下载。您应该注意目录名称是否为img download或者脚本和您这个目录是否在相同文件夹下，又应是您的url传入错误等等...

ps:没想到真的有人会用这个脚本这是让我最震撼的，我就是拿来练练手写的这个脚本，从其中的语法和差错检测就知道这是萌新写的。如果您还有需求，我会尝试优化这个下载脚本。（写的垃圾居然有人用！太开心了）

**Comment by gMan1990** [comment]
@emptysuns 随便查看一张图，图片是错乱的

**Comment by emptysuns** [comment]
能否再详细描述一下您的问题？比如什么是错乱的，是下载下来的图片有缺陷错乱无法正常显示，还是图片的名称错乱。
能否方便，提供一下截图，供参考。

**Comment by gMan1990** [comment]
@emptysuns 对不起，我没描述清楚。比如下载到的`00001.jpg`这张图，你打开来看，正常结果应该是一个妹子 ( 就像 #1 所说 )

**Comment by emptysuns** [comment]
您好，已经更新了脚本。对下载后，所得资源进行了处理，并且优化了脚本使用效果，请您再次试试效果（可从release中直接下载打包好的exe使用）。现在应该不会有错乱的情况出现了。
