### ISSUE TITLE
这个脚本很好用

### ISSUE THREAD

**Issue by jiekai0629** [emptysuns/18comic-Download#3]
不过有个问题就是假如是多集的本子就不能一次过下到完
我试了下韩漫只下载第一章
不过整体效果很好跑超快

**Comment by emptysuns** [comment]
多章的问题挺好解决的，你可以自己试着通过解析那个选页的html得到url就行了，或者等我下次更新，我会试着加入下多章的。
因为这个东西是为了我方便写的，没太多花精力，只根据我的需求写的，功能可能有点不足。

**Comment by emptysuns** [comment]
您好，我已经增加了，下载多话的功能，您可以测试一下。
ps：我看见您发了两个issue这个就关了
