### ISSUE TITLE
缺点在于韩漫只能下载一个而不是一套的，通常下载后都是下载最前面的第一集

### ISSUE THREAD

**Issue by jiekai0629** [emptysuns/18comic-Download#4]
缺点在于韩漫只能下载一个而不是一套的，通常下载后都是下载最前面的第一集

**Comment by emptysuns** [comment]
啊，我不怎么看韩国的没注意到

**Comment by emptysuns** [comment]
您好，我已经增加了下载多话的功能，您可以测试一下。欢迎使用反馈！

**Comment by jiekai0629** [comment]
很好用  真香呀  期待您后续搞得代码脚本

**Comment by jiekai0629** [comment]
有新的问题了  下载到第四集的时候  会出现错误  第一次是直接卡住跳eror  
第二次是直接跳出  我就只是按alt+tab建 看看而已  
不信邪第三次又在试了试  还是一样
下到第五集时跳出一堆的代码  转了一下子就退出了
