### ISSUE TITLE
能下载  新的问题在于  下后再达到第五集时会出现闪退亦或者卡住error的情况

### ISSUE THREAD

**Issue by jiekai0629** [emptysuns/18comic-Download#5]
试了几下还是一样

**Comment by jiekai0629** [comment]
状况比较好了  我有试了几天  某个大佬说过爬虫这种IO密集型操作好像使用多线程比较合适

缺失下载速度快了许多许多  可是缺点在于还是会出页数缺失的情况（相反的你的脚本完全不存在页数缺失的情况）

**Comment by emptysuns** [comment]
对于以上问题解释如下:
1、先说闪退、error问题。我在本地测试没有出现过这种问题，方便提供一下出现问题的连接吗，方便修bug。
2、这个脚本本身就是用的多线程。使用mutiprocessing库的Pool来实现的。您可以看一下代码。
3、对于缺页现象的情况解释。这个存储comic的服务器，估计是设置着连接限制的吧，当每一个ip在一定时间内过多连接会进行一定限制（不断试错时发现的），这就导致缺页，我在代码中可以清楚的看到加入了差错检测，虽然对异常处理的很狂野，不过基本上没问题，出现下不了的时候会自动进行重新下载。（要不就是你梯子网络有问题或者它服务器网络有问题，网络这种东西本来就是看脸，这种东西只有它的运维才知道了）

**Comment by emptysuns** [comment]
**猜测闪退问题：**
你可以在每次下载后手动关闭pool
在main()方法最后一行print()输出信息后，加入一行代码
`pool.close()`
来关闭pool减少内存占用，不影响使用。应该是这个问题，我没有做实际测试。如果您测试后，闪退解决，请反馈一下效果。（我多方面测试后，并未出现闪退问题，无从下手解决，应该是少打了这一行代码的问题）

**Comment by emptysuns** [comment]
现将多进程改为多线程，来解决io密集情况下，cpu处理能力跟不上的问题。请测试看看，如果没问题将这个issue关了吧。

**Comment by jiekai0629** [comment]
> 试了几下还是一样
